ALTER TABLE "UserProfile" ADD COLUMN IF NOT EXISTS "iban" TEXT;
ALTER TABLE "UserProfile" ADD COLUMN IF NOT EXISTS "behanceUrl" TEXT;
ALTER TABLE "UserProfile" ADD COLUMN IF NOT EXISTS "dribbbleUrl" TEXT;
ALTER TABLE "UserProfile" ADD COLUMN IF NOT EXISTS "linkedinUrl" TEXT;
ALTER TABLE "UserProfile" ADD COLUMN IF NOT EXISTS "websiteUrl" TEXT;

